### ISSUE TITLE
Script broken

### ISSUE THREAD

**Issue by 1busyguy** [fropych/mine-diffusion#1]
Error loading script: main.py
Traceback (most recent call last):
  File "D:\For Profit Businesses\Artifical Inteligence Artwork\BackUp old version\stable-diffusion-webui\modules\scripts.py", line 218, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\For Profit Businesses\Artifical Inteligence Artwork\BackUp old version\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "D:\For Profit Businesses\Artifical Inteligence Artwork\BackUp old version\stable-diffusion-webui\extensions\mine-diffusion\scripts\main.py", line 9, in <module>
    EXT_DIR = Path(__file__).parent
NameError: name '__file__' is not defined

**Comment by fropych** [comment]
try updating the extension

**Comment by fropych** [comment]
why don't you have ```EXT_DIR = Path(__file__).parent.parent``` ?

**Comment by 1busyguy** [comment]
![mine_diffusion](https://user-images.githubusercontent.com/807880/218373631-57427852-47e2-499a-b6fd-14e93744c70c.PNG)
no tab is created when installed - 
why don't you have EXT_DIR = Path(__file__).parent.parent ?  - where do I configure this?

**Comment by fropych** [comment]
this should be the default. try to click "check for updates" or see what you have on line 9 in the file D:\For Profit Businesses\Artificial Intelligence Artwork\Backup old version\stable-diffusion-webui\extensions\mine-diffusion\scripts\main.py and replace with ```EXT_DIR = Path(__file__).parent.parent```

**Comment by 1busyguy** [comment]
I updated it - and it still doesn't work  ;(

**Comment by fropych** [comment]
I changed the way to get extension path, try now
